language: objective-c
rvm: 1.9.3

before_install:
  - gem install cocoapods -v '0.32.1'
  - pod repo remove master
  - pod setup

env:
  global:
    secure: c+26kMaU9GeSA1Jppwom8YdFrNSHTKmuoelIvOVzoSoneoOSBnWXYD192O1MtczhM+AAjsCo9FBflRnHANzLXpgqfwRYu2fVfuCL5CKmA2bA53dZIM6QJxx12afIeJL5RV2k3lhpDltjkCJVkraakoAhG988bq1vPuq9AaoPGRg=

script:
- make build
